---

version: "3"
services:
  pronto:
    build: .
    image: akirchner/pronto-docker:latest
    volumes:
      - .:/lint_app
    environment:
      - LC_ALL=C.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - PRONTO_BITBUCKET_USERNAME
      - PRONTO_BITBUCKET_PASSWORD
