source "https://rubygems.org"

gem "pronto"
gem "pronto-brakeman"
gem "pronto-erb_lint"
gem "pronto-eslint_npm"
gem "pronto-fasterer"
gem "pronto-rails_best_practices"
gem "pronto-rails_schema"
gem "pronto-reek"
gem "pronto-rubocop"
gem "pronto-stylelint"
